version: "1.0"
info:
  model: int-scaffold
packages:
- name: JohnsProjectProject
  gitServerName: JohnPCarter
  gitUrl: https://github.com/johnpcarter/JohnsProjectProject
  gitUsername: johnpcarter
  gitBranch: main
