version: "1.0"
info:
  model: int-scaffold
packages:
- name: JohnsProjectProject
  gitServerName: JohnPCarter
  gitUrl: https://github.com/johnpcarter/JohnsProjectProject
  gitUsername: johnpcarter
  gitBranch: main
services:
- serviceName: project.johnsproject.integrations:test
  packages:
  - name: JohnsProjectProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.786
- serviceName: project.johnsproject.integrations:dfsfdsfsfs
  packages:
  - name: JohnsProjectProject
    version: "1.0"
- serviceName: pub.compress:decompressData
  packages:
  - name: WmPublic
    version: 11.0.0.0.792
- serviceName: project.johnsproject.integrations:xvsdfsdfsf
  packages:
  - name: JohnsProjectProject
    version: "1.0"
